pipeline {
    agent any
    stages {
        stage('Build') {
            steps {

                sh 
            }
            }
            steps {
                sh 'gradle --version'
            }
        }
    }