pipeline {
  environment {
    registry = "karimomar71/node-app"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any

        stages {
            stage('Cloning Git') {
                steps {
                    git 'https://github.com/karimomar71/nodejs__app'
                }
            }
            stage('Building our image'){
            steps {
            
                sh "docker build . -t karimomar71/node-app:$BUILD_NUMBER" 
            }
            }
            stage('Deploy Image') {
                steps{
                    script {
                        docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                    }
            }
            }
            stage('Remove Unused docker image') {
                steps{
                    sh "docker rmi $registry:$BUILD_NUMBER"
                }
            }
        }
        }